services:
  server:
    image: server-image
    build: ./Server
    ports:
      - "5000:5000"
      - "8000:8000"
      - "5678:5678"
    volumes:
      - ./Server:/app
    working_dir: /app
    # command: python -m debugpy --listen 0.0.0.0:5678 --wait-for-client main.py
    command: python main.py
    environment:
      - SUBSCRIBED_POWER=57200

  client:
    image: client-image
    build: ./Client
    depends_on:
      - server
    volumes:
      - ./Client:/app
      - ./Data:/data
      - client-shared:/shared
    working_dir: /app
    entrypoint: ["./entrypoint.sh"]
    environment:
      - JOB_CHOICES=xsbench minife comd
      - DELAY_START=15
      - DELAY_STEP=2
      - HPC_MANAGER_HOST=192.168.2.111
      - HPC_MANAGER_PORT=8000
      - HPC_MANAGER_FLASK_SERVER_PORT=5000
    

volumes:
  client-shared:
